// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repaso1ERParcial.DAL;

namespace Repaso1ERParcial.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210927204100_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("Repaso1ERParcial.Entidades.Colores", b =>
                {
                    b.Property<int>("ColoresId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("ColoresId");

                    b.ToTable("Colores");
                });
#pragma warning restore 612, 618
        }
    }
}
